# Generated by Django 6.0.6 on 2026-09-02 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0004_cardprinting_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='DeckEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_entries', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='decks.deck')),
            ],
        ),
        migrations.CreateModel(
            name='DeckLegend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deck_legend_entries', to='cards.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legends', to='decks.deck')),
            ],
        ),
        migrations.AddConstraint(
            model_name='deck',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='decks_unique_owner_slug'),
        ),
        migrations.AddConstraint(
            model_name='deckentry',
            constraint=models.UniqueConstraint(fields=('deck', 'card'), name='decks_unique_entry_per_deck'),
        ),
        migrations.AddConstraint(
            model_name='deckentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='decks_entry_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='decklegend',
            constraint=models.UniqueConstraint(fields=('deck', 'card'), name='decks_unique_legend_per_deck'),
        ),
    ]
