# Generated by Django 6.0.6 on 2026-09-02

import django.db.models.deletion
from django.db import migrations, models


def create_editorial_profiles(apps, schema_editor):
    Deck = apps.get_model("decks", "Deck")
    DeckEditorialProfile = apps.get_model("decks", "DeckEditorialProfile")
    DeckEditorialProfile.objects.bulk_create(
        [DeckEditorialProfile(deck_id=deck_id) for deck_id in Deck.objects.values_list("id", flat=True)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckEditorialProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archetype", models.CharField(blank=True, max_length=160)),
                ("short_summary", models.CharField(blank=True, max_length=320)),
                ("strategy_overview", models.TextField(blank=True)),
                ("game_plan", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("weaknesses", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deck", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="editorial_profile", to="decks.deck")),
            ],
        ),
        migrations.RunPython(create_editorial_profiles, migrations.RunPython.noop),
        migrations.CreateModel(
            name="DeckKeyCard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("editorial_note", models.TextField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("card", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deck_key_card_entries", to="cards.card")),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="key_cards", to="decks.deckeditorialprofile")),
            ],
            options={"ordering": ("display_order", "card__name")},
        ),
        migrations.AddConstraint(
            model_name="deckkeycard",
            constraint=models.UniqueConstraint(fields=("profile", "card"), name="decks_unique_key_card_per_profile"),
        ),
    ]
