# Generated by Django 6.0.6 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("decks", "0002_editorial_profile_and_key_cards")]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="editorial_status",
            field=models.CharField(
                choices=[("DRAFT", "Borrador"), ("PUBLISHED", "Publicado"), ("ARCHIVED", "Archivado")],
                default="DRAFT",
                max_length=10,
            ),
        ),
    ]
