# Generated by Django 6.0.6 on 2026-09-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('youtube_url', models.URLField()),
                ('youtube_video_id', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_articles', models.ManyToManyField(blank=True, related_name='videos', to='content.article')),
            ],
            options={
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
