# Generated by Django 6.0.6 on 2026-09-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decks", "0002_editorial_profile_and_key_cards"),
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="related_decks",
            field=models.ManyToManyField(blank=True, related_name="related_videos", to="decks.deck"),
        ),
    ]
