# Generated by Django 6.0.6 on 2026-09-02 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('card_type', models.CharField(choices=[('LEGEND', 'Legend'), ('UNIT', 'Unit'), ('PROGRAM', 'Program'), ('GEAR', 'Gear')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEWED', 'Revisado'), ('PUBLISHED', 'Publicado')], default='DRAFT', max_length=10)),
                ('collector_number', models.CharField(blank=True, max_length=60)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('rules_text', models.TextField(blank=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='cards.set')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
