# Generated by Django 6.0.6 on 2026-09-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPrinting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_number', models.CharField(blank=True, max_length=60)),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
                ('ram', models.PositiveIntegerField(blank=True, null=True)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('printing_label', models.CharField(blank=True, max_length=160)),
                ('is_primary', models.BooleanField(default=False)),
                ('source_name', models.CharField(blank=True, max_length=160)),
                ('source_url', models.URLField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printings', to='cards.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printings', to='cards.set')),
            ],
            options={
                'ordering': ('card__name', 'set__name', 'collector_number'),
            },
        ),
    ]
