# Generated by Django 6.0.6 on 2026-09-02 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_migrate_cards_to_initial_printings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='collector_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='card',
            name='power',
        ),
        migrations.RemoveField(
            model_name='card',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='card',
            name='set',
        ),
    ]
